language: c

os: 
    - osx
    - linux

before_install: 
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ;fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install snaipe/soft/criterion ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; add-apt-repository ppa:snaipewastaken/ppa ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; apt-get update ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; apt-get install criterion-dev ;fi 

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
