language: c

os: 
    - osx

before_install:
    - if [ ${TRAVIS_OS_NAME} = "osx" ] ; then brew update; fi
    - brew install snaipe/soft/criterion

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
